// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/dist/lib/metadata/types/metadata-interface.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../app/about/page.tsx
{
  const handler = {} as typeof import("../../app/about/page.js")
  handler satisfies AppPageConfig<"/about">
}

// Validate ../../app/admin-pengelola/page.tsx
{
  const handler = {} as typeof import("../../app/admin-pengelola/page.js")
  handler satisfies AppPageConfig<"/admin-pengelola">
}

// Validate ../../app/admin/page.tsx
{
  const handler = {} as typeof import("../../app/admin/page.js")
  handler satisfies AppPageConfig<"/admin">
}

// Validate ../../app/blog/[slug]/page.tsx
{
  const handler = {} as typeof import("../../app/blog/[slug]/page.js")
  handler satisfies AppPageConfig<"/blog/[slug]">
}

// Validate ../../app/blog/page.tsx
{
  const handler = {} as typeof import("../../app/blog/page.js")
  handler satisfies AppPageConfig<"/blog">
}

// Validate ../../app/browse-template/[slug]/page.tsx
{
  const handler = {} as typeof import("../../app/browse-template/[slug]/page.js")
  handler satisfies AppPageConfig<"/browse-template/[slug]">
}

// Validate ../../app/browse-template/page.tsx
{
  const handler = {} as typeof import("../../app/browse-template/page.js")
  handler satisfies AppPageConfig<"/browse-template">
}

// Validate ../../app/forgot-password/page.tsx
{
  const handler = {} as typeof import("../../app/forgot-password/page.js")
  handler satisfies AppPageConfig<"/forgot-password">
}

// Validate ../../app/login/page.tsx
{
  const handler = {} as typeof import("../../app/login/page.js")
  handler satisfies AppPageConfig<"/login">
}

// Validate ../../app/page.tsx
{
  const handler = {} as typeof import("../../app/page.js")
  handler satisfies AppPageConfig<"/">
}

// Validate ../../app/signup/page.tsx
{
  const handler = {} as typeof import("../../app/signup/page.js")
  handler satisfies AppPageConfig<"/signup">
}

// Validate ../../app/super-admin/page.tsx
{
  const handler = {} as typeof import("../../app/super-admin/page.js")
  handler satisfies AppPageConfig<"/super-admin">
}

// Validate ../../app/verify-email/page.tsx
{
  const handler = {} as typeof import("../../app/verify-email/page.js")
  handler satisfies AppPageConfig<"/verify-email">
}

// Validate ../../app/api/auth/github/route.ts
{
  const handler = {} as typeof import("../../app/api/auth/github/route.js")
  handler satisfies RouteHandlerConfig<"/api/auth/github">
}

// Validate ../../app/api/auth/google/callback/route.ts
{
  const handler = {} as typeof import("../../app/api/auth/google/callback/route.js")
  handler satisfies RouteHandlerConfig<"/api/auth/google/callback">
}

// Validate ../../app/api/auth/google/route.ts
{
  const handler = {} as typeof import("../../app/api/auth/google/route.js")
  handler satisfies RouteHandlerConfig<"/api/auth/google">
}

// Validate ../../app/api/auth/login/route.ts
{
  const handler = {} as typeof import("../../app/api/auth/login/route.js")
  handler satisfies RouteHandlerConfig<"/api/auth/login">
}

// Validate ../../app/api/auth/logout/route.ts
{
  const handler = {} as typeof import("../../app/api/auth/logout/route.js")
  handler satisfies RouteHandlerConfig<"/api/auth/logout">
}

// Validate ../../app/api/auth/me/route.ts
{
  const handler = {} as typeof import("../../app/api/auth/me/route.js")
  handler satisfies RouteHandlerConfig<"/api/auth/me">
}

// Validate ../../app/api/auth/register/route.ts
{
  const handler = {} as typeof import("../../app/api/auth/register/route.js")
  handler satisfies RouteHandlerConfig<"/api/auth/register">
}

// Validate ../../app/api/auth/reset-password/route.ts
{
  const handler = {} as typeof import("../../app/api/auth/reset-password/route.js")
  handler satisfies RouteHandlerConfig<"/api/auth/reset-password">
}

// Validate ../../app/api/cms/content/route.ts
{
  const handler = {} as typeof import("../../app/api/cms/content/route.js")
  handler satisfies RouteHandlerConfig<"/api/cms/content">
}

// Validate ../../app/api/cms/templates/route.ts
{
  const handler = {} as typeof import("../../app/api/cms/templates/route.js")
  handler satisfies RouteHandlerConfig<"/api/cms/templates">
}

// Validate ../../app/api/otp/request/route.ts
{
  const handler = {} as typeof import("../../app/api/otp/request/route.js")
  handler satisfies RouteHandlerConfig<"/api/otp/request">
}

// Validate ../../app/api/otp/verify/route.ts
{
  const handler = {} as typeof import("../../app/api/otp/verify/route.js")
  handler satisfies RouteHandlerConfig<"/api/otp/verify">
}

// Validate ../../app/api/payments/doku/checkout/route.ts
{
  const handler = {} as typeof import("../../app/api/payments/doku/checkout/route.js")
  handler satisfies RouteHandlerConfig<"/api/payments/doku/checkout">
}

// Validate ../../app/api/super-admin/data/route.ts
{
  const handler = {} as typeof import("../../app/api/super-admin/data/route.js")
  handler satisfies RouteHandlerConfig<"/api/super-admin/data">
}

// Validate ../../app/api/super-admin/logs/route.ts
{
  const handler = {} as typeof import("../../app/api/super-admin/logs/route.js")
  handler satisfies RouteHandlerConfig<"/api/super-admin/logs">
}

// Validate ../../app/api/super-admin/settings/route.ts
{
  const handler = {} as typeof import("../../app/api/super-admin/settings/route.js")
  handler satisfies RouteHandlerConfig<"/api/super-admin/settings">
}

// Validate ../../app/api/super-admin/users/[id]/reset-password/route.ts
{
  const handler = {} as typeof import("../../app/api/super-admin/users/[id]/reset-password/route.js")
  handler satisfies RouteHandlerConfig<"/api/super-admin/users/[id]/reset-password">
}

// Validate ../../app/api/super-admin/users/[id]/route.ts
{
  const handler = {} as typeof import("../../app/api/super-admin/users/[id]/route.js")
  handler satisfies RouteHandlerConfig<"/api/super-admin/users/[id]">
}

// Validate ../../app/api/super-admin/users/route.ts
{
  const handler = {} as typeof import("../../app/api/super-admin/users/route.js")
  handler satisfies RouteHandlerConfig<"/api/super-admin/users">
}





// Validate ../../app/about/layout.tsx
{
  const handler = {} as typeof import("../../app/about/layout.js")
  handler satisfies LayoutConfig<"/about">
}

// Validate ../../app/blog/layout.tsx
{
  const handler = {} as typeof import("../../app/blog/layout.js")
  handler satisfies LayoutConfig<"/blog">
}

// Validate ../../app/browse-template/[slug]/layout.tsx
{
  const handler = {} as typeof import("../../app/browse-template/[slug]/layout.js")
  handler satisfies LayoutConfig<"/browse-template/[slug]">
}

// Validate ../../app/browse-template/layout.tsx
{
  const handler = {} as typeof import("../../app/browse-template/layout.js")
  handler satisfies LayoutConfig<"/browse-template">
}

// Validate ../../app/layout.tsx
{
  const handler = {} as typeof import("../../app/layout.js")
  handler satisfies LayoutConfig<"/">
}
