var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/login/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__051eba25._.js")
R.c("server/chunks/ssr/node_modules_next_dist_d0b0ee8f._.js")
R.c("server/chunks/ssr/[root-of-the-server]__d1debd57._.js")
R.c("server/chunks/ssr/node_modules_next_dist_cf0288a0._.js")
R.c("server/chunks/ssr/app_0ef037c1._.js")
R.c("server/chunks/ssr/lib_metadata_ts_be4ca681._.js")
R.c("server/chunks/ssr/[root-of-the-server]__43a676e8._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_9774470f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_45780354.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/[root-of-the-server]__020556dc._.js")
R.c("server/chunks/ssr/_fdc41e1b._.js")
R.c("server/chunks/ssr/_3c63532a._.js")
R.m(73485)
R.m(27748)
module.exports=R.m(27748).exports
