var R=require("../../chunks/[turbopack]_runtime.js")("server/app/favicon.ico/route.js")
R.c("server/chunks/[root-of-the-server]__becc00f7._.js")
R.c("server/chunks/node_modules_next_dist_b31d17ed._.js")
R.c("server/chunks/node_modules_next_dist_3bd4d890._.js")
R.c("server/chunks/node_modules_next_dist_1558b63e._.js")
R.c("server/chunks/node_modules_next_dist_esm_build_templates_app-route_c9e548b7.js")
R.c("server/chunks/[root-of-the-server]__7e0f8ee4._.js")
R.m(15934)
R.m(90295)
module.exports=R.m(90295).exports
